### ISSUE TITLE
HIDtoVPAD Version?

### ISSUE THREAD

**Issue by pussinboot** [QuarkTheAwesome/HIDtoVPADNetworkClient#1]
hi, has a version of HIDtoVPAD with network support been released? I see you're sending fake HID packets over tcp/udp to certain ports on the wii u but looking through the HIDtoVPAD code I don't see any networking code

**Comment by QuarkTheAwesome** [comment]
Maschell sent me a pre-release version of HID to VPAD to work with that
contained networking code. I'm not sure if this code has made it public
yet, but it's in the works. It's worth noting that he's forked this repo
and is continuing it himself.

**Comment by pussinboot** [comment]
cool thanks, i'll eagerly await his release then : )
