### ISSUE TITLE
Network Client interfering with Microphone?

### ISSUE THREAD

**Issue by DivineJayce** [QuarkTheAwesome/HIDtoVPADNetworkClient#22]
Currently using v0.4 Stable:

Yo Maschell it's PeekingBoo!
I've had this issue persist since day 1 but I finally decided to investigate it, I have found that when the network client connects to my Wii U over wifi my microphone starts making popping noises.

This doesn't happen when the client is open, only when it is connected to the Wii U.
Is there anything you can think of within the software itself that could be causing this?
I can't find any reliable source about wifi interference and I have other devices like phones connected to wifi too. It only occurs while this client is connected.

An example of what I mean can be heard in this clip at the 13s mark where I say "pogs in chat":
https://clips.twitch.tv/MuddyObedientCurlewBudStar

The mic sort of skipped a bit when I said the word "chat" and usually does it every few seconds, though it's only noticeable when I talk.

Any help would be fantastic because I have tried everything I can think to, short of purchasing a LAN adapter for my Wii U.

**Comment by Maschell** [comment]
Did you try to disable the "Automatically scan for controllers" feature in the options?

**Comment by DivineJayce** [comment]
THANK YOU SO MUCH!

**Comment by Maschell** [comment]
Then it looks like it wasn't an issue with your wi-fi connection but the USB on your PC. The network client is automatically searching for new devices every few seconds (for plug'n play) which can cause some "lag".
